In [1]:
import pandas as pd

In [49]:
ventas = pd.read_excel("/content/Ventas 1.xlsx")

In [50]:
ventas

,IdCliente,NombreCliente,Fecha,Empleado,Referencia,Descripcion,CodigoFamilia,Familia,Cantidad,Ventas,Localidad,Sede,Area
0,C1070956433,PINTO JOHN,2016-09-01,24.0,LL-2R-0038,PILOT STREET 110/80-17,101.0,LLANTA,1.0,129310,Puente aranda,Calle 13,35.0
1,C1032372566,CESAR CRUZ,2016-09-01,14.0,LL-TCA-0133,TOURING 175/70R13,101.0,LLANTA,2.0,181034,Suba,Suba,32.0
2,C2865810,PINEDA JAIME,2016-09-01,12.0,LL-TCA-0019,ENERGY XM2 185/65R14,101.0,LLANTA,1.0,193095,Usaquen,Santa ana,33.0
3,C11210285,VILLALBA RODRIGUEZ FABIO,2016-09-01,24.0,LL-TCA-0009,ENERGY XM2 165/65R13,101.0,LLANTA,2.0,262069,Puente aranda,Calle 13,35.0
4,C80755314,MOLINA RONALD,2016-09-01,14.0,LL-TCA-0132,NO UTILIZAR,101.0,LLANTA,4.0,362069,Suba,Suba,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127261,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127262,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127263,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127264,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127265,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN

In [51]:
# Verificando filas con nulos
filas_nulas = ventas[ventas.isnull().any(axis=1)]
filas_nulas

,IdCliente,NombreCliente,Fecha,Empleado,Referencia,Descripcion,CodigoFamilia,Familia,Cantidad,Ventas,Localidad,Sede,Area
127255,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127256,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127257,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127258,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127259,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127260,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127261,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127262,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127263,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127264,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
127265,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,NaN

In [52]:
# Cantidad de nulos por columnas
ventas.isna().sum()

IdCliente        11
NombreCliente    11
Fecha            11
Empleado         11
Referencia       11
Descripcion      11
CodigoFamilia    11
Familia          11
Cantidad         11
Ventas           11
Localidad        11
Sede             10
Area             11
dtype: int64

In [53]:
# Eliminamos nulos
ventas = ventas.dropna()

In [54]:
# Verificamos que no existen nulos
ventas.isna().sum()

IdCliente        0
NombreCliente    0
Fecha            0
Empleado         0
Referencia       0
Descripcion      0
CodigoFamilia    0
Familia          0
Cantidad         0
Ventas           0
Localidad        0
Sede             0
Area             0
dtype: int64

In [55]:
# Revisamos los tipos de datos
ventas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 127255 entries, 0 to 127254
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   IdCliente      127255 non-null  object
 1   NombreCliente  127255 non-null  object
 2   Fecha          127255 non-null  datetime64[ns]
 3   Empleado       127255 non-null  float64
 4   Referencia     127255 non-null  object
 5   Descripcion    127255 non-null  object
 6   CodigoFamilia  127255 non-null  float64
 7   Familia        127255 non-null  object
 8   Cantidad       127255 non-null  float64
 9   Ventas         127255 non-null  object
 10  Localidad      127255 non-null  object
 11  Sede           127255 non-null  object
 12  Area           127255 non-null  float64
dtypes: datetime64[ns](1), float64(4), object(8)
memory usage: 13.6+ MB

In [56]:
# Convertir  a enteros y flotantes
ventas["Empleado"] = ventas["Empleado"].astype(int)
ventas["Ventas"] = ventas["Ventas"].astype(float)

<ipython-input-56-7286a028cc06>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas["Empleado"] = ventas["Empleado"].astype(int)

ValueError: ignored

In [57]:
# Se ratifica que Ventas es string
ventas['Ventas'] = ventas['Ventas'].astype(str)

# Usamos str.contains() para buscar registros con comas o puntos en la columna 'Ventas'
registros_con_comas_o_puntos = ventas[ventas['Ventas'].str.contains('[,.]')]

# Mostramos los registros encontrados y vemos que existen 5. Se ve que sobran dos ceros después de la coma
registros_con_comas_o_puntos

<ipython-input-57-4cc9e884256e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas['Ventas'] = ventas['Ventas'].astype(str)

,IdCliente,NombreCliente,Fecha,Empleado,Referencia,Descripcion,CodigoFamilia,Familia,Cantidad,Ventas,Localidad,Sede,Area
6720,C830060151,SISTEMA INTEGRADO DE TRANSPORTE SI99 SA,2016-11-10,2,LL-PLC-0042,X INCITY XZU3+ 295/80R22.5,101.0,LLANTA,50.0,"70.000.001,00",Engativa,Ventas externas,22.0
6721,C830060151,SISTEMA INTEGRADO DE TRANSPORTE SI99 SA,2016-11-10,2,LL-PLC-0042,X INCITY XZU3+ 295/80R22.5,101.0,LLANTA,50.0,"70.000.001,00",Engativa,Ventas externas,22.0
45141,C830044266,DAIMLER COLOMBIA SA,2017-12-09,2,LL-PLC-0045,X MULTI D 275/80R22.5,101.0,LLANTA,80.0,"74.511.448,00",Engativa,Ventas externas,22.0
58461,C890930545,MINCIVIL S A,2018-04-14,3,LL-PLC-0052,X WORKS XDY 12R22.5,101.0,LLANTA,58.0,"74.158.398,00",Engativa,Ventas externas,22.0
78818,C900365651,EMPRESA DE TRANSPORTE INTEGRADO DE BOGOTA ETIB...,2018-11-14,2,LL-PLB-0031,XZE2 215/75 R17.5,101.0,LLANTA,130.0,"65.321.270,00",Engativa,Ventas externas,22.0

In [58]:
# Función para eliminar los ceros a la derecha de la coma
def eliminar_ceros_despues_coma(cadena):
    if ',' in cadena:
        partes = cadena.split(',')
        parte_despues_coma = partes[1].rstrip('0')
        return partes[0] + (',' + parte_despues_coma if parte_despues_coma else '')
    return cadena

# Aplicamos la función y volvemos a guardar
ventas['Ventas']= ventas['Ventas'].apply(eliminar_ceros_despues_coma)

<ipython-input-58-4989c982fdb3>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas['Ventas']= ventas['Ventas'].apply(eliminar_ceros_despues_coma)

In [60]:
# Utiliza el método loc para seleccionar los registros con los índices 6720, 6721, 45141, 58461 y 78818 para verificar los cambios
indices_a_buscar = [6720, 6721, 45141, 58461, 78818]
registros_seleccionados = ventas.loc[indices_a_buscar]

registros_seleccionados

,IdCliente,NombreCliente,Fecha,Empleado,Referencia,Descripcion,CodigoFamilia,Familia,Cantidad,Ventas,Localidad,Sede,Area
6720,C830060151,SISTEMA INTEGRADO DE TRANSPORTE SI99 SA,2016-11-10,2,LL-PLC-0042,X INCITY XZU3+ 295/80R22.5,101.0,LLANTA,50.0,70.000.001,Engativa,Ventas externas,22.0
6721,C830060151,SISTEMA INTEGRADO DE TRANSPORTE SI99 SA,2016-11-10,2,LL-PLC-0042,X INCITY XZU3+ 295/80R22.5,101.0,LLANTA,50.0,70.000.001,Engativa,Ventas externas,22.0
45141,C830044266,DAIMLER COLOMBIA SA,2017-12-09,2,LL-PLC-0045,X MULTI D 275/80R22.5,101.0,LLANTA,80.0,74.511.448,Engativa,Ventas externas,22.0
58461,C890930545,MINCIVIL S A,2018-04-14,3,LL-PLC-0052,X WORKS XDY 12R22.5,101.0,LLANTA,58.0,74.158.398,Engativa,Ventas externas,22.0
78818,C900365651,EMPRESA DE TRANSPORTE INTEGRADO DE BOGOTA ETIB...,2018-11-14,2,LL-PLB-0031,XZE2 215/75 R17.5,101.0,LLANTA,130.0,65.321.270,Engativa,Ventas externas,22.0

In [61]:
# Revisamos el dataframe
ventas

,IdCliente,NombreCliente,Fecha,Empleado,Referencia,Descripcion,CodigoFamilia,Familia,Cantidad,Ventas,Localidad,Sede,Area
0,C1070956433,PINTO JOHN,2016-09-01,24,LL-2R-0038,PILOT STREET 110/80-17,101.0,LLANTA,1.0,129310,Puente aranda,Calle 13,35.0
1,C1032372566,CESAR CRUZ,2016-09-01,14,LL-TCA-0133,TOURING 175/70R13,101.0,LLANTA,2.0,181034,Suba,Suba,32.0
2,C2865810,PINEDA JAIME,2016-09-01,12,LL-TCA-0019,ENERGY XM2 185/65R14,101.0,LLANTA,1.0,193095,Usaquen,Santa ana,33.0
3,C11210285,VILLALBA RODRIGUEZ FABIO,2016-09-01,24,LL-TCA-0009,ENERGY XM2 165/65R13,101.0,LLANTA,2.0,262069,Puente aranda,Calle 13,35.0
4,C80755314,MOLINA RONALD,2016-09-01,14,LL-TCA-0132,NO UTILIZAR,101.0,LLANTA,4.0,362069,Suba,Suba,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127250,C891100881,MORENO VARGAS SOCIEDAD ANONIMA,2020-03-10,2,LL-PLC-0159,X WORKS HD XDY 12R22.5,101.0,LLANTA,4.0,5635766,Engativa,Ventas externas,22.0
127251,C900364615,ORGANIZACION SUMA SAS,2020-03-10,1,LL-PLB-0024,X MULTI Z 235/75R17.5,101.0,LLANTA,9.0,6894000,Engativa,Ventas externas,22.0
127252,C900365651,EMPRESA DE TRANSPORTE INTEGRADO DE BOGOTA ETIB...,2020-03-10,2,LL-PLB-0024,X MULTI Z 235/75R17.5,101.0,LLANTA,20.0,11955636,Engativa,Ventas externas,22.0
127253,C900365651,EMPRESA DE TRANSPORTE INTEGRADO DE BOGOTA ETIB...,2020-03-10,2,LL-PLB-0031,XZE2 215/75 R17.5,101.0,LLANTA,30.0,15908063,Engativa,Ventas externas,22.0
127254,C900364615,ORGANIZACION SUMA SAS,2020-03-10,1,LL-PLC-0074,X MULTI Z 295/80R22.5,101.0,LLANTA,14.0,21868000,Engativa,Ventas externas,22.0

In [62]:
# Valores de ventas
ventas["Ventas"].unique()

array(['129310', '181034', '193095', ..., '11955636', '15908063',
       '21868000'], dtype=object)

In [63]:
# Tipos de datos de cada columna
ventas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 127255 entries, 0 to 127254
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   IdCliente      127255 non-null  object
 1   NombreCliente  127255 non-null  object
 2   Fecha          127255 non-null  datetime64[ns]
 3   Empleado       127255 non-null  int64
 4   Referencia     127255 non-null  object
 5   Descripcion    127255 non-null  object
 6   CodigoFamilia  127255 non-null  float64
 7   Familia        127255 non-null  object
 8   Cantidad       127255 non-null  float64
 9   Ventas         127255 non-null  object
 10  Localidad      127255 non-null  object
 11  Sede           127255 non-null  object
 12  Area           127255 non-null  float64
dtypes: datetime64[ns](1), float64(3), int64(1), object(8)
memory usage: 17.6+ MB

In [66]:
# Confirmamos que Ventas sea string
ventas['Ventas'] = ventas['Ventas'].astype(str)

# Función para eliminar comas y puntos en cada fila de la columna 'Ventas'
ventas['Ventas'] = ventas['Ventas'].apply(lambda x: x.replace(',', '').replace('.', ''))

# Convertimos de string  a float
ventas['Ventas'] = ventas['Ventas'].astype(float)

# Puedes mostrar el DataFrame actualizado
ventas

<ipython-input-66-7cec6acbf0f8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas['Ventas'] = ventas['Ventas'].astype(str)
<ipython-input-66-7cec6acbf0f8>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas['Ventas'] = ventas['Ventas'].apply(lambda x: x.replace(',', '').replace('.', ''))
<ipython-input-66-7cec6acbf0f8>:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas['Ventas'] = ventas['Ventas'].astype(float)

,IdCliente,NombreCliente,Fecha,Empleado,Referencia,Descripcion,CodigoFamilia,Familia,Cantidad,Ventas,Localidad,Sede,Area
0,C1070956433,PINTO JOHN,2016-09-01,24,LL-2R-0038,PILOT STREET 110/80-17,101.0,LLANTA,1.0,129310.0,Puente aranda,Calle 13,35.0
1,C1032372566,CESAR CRUZ,2016-09-01,14,LL-TCA-0133,TOURING 175/70R13,101.0,LLANTA,2.0,181034.0,Suba,Suba,32.0
2,C2865810,PINEDA JAIME,2016-09-01,12,LL-TCA-0019,ENERGY XM2 185/65R14,101.0,LLANTA,1.0,193095.0,Usaquen,Santa ana,33.0
3,C11210285,VILLALBA RODRIGUEZ FABIO,2016-09-01,24,LL-TCA-0009,ENERGY XM2 165/65R13,101.0,LLANTA,2.0,262069.0,Puente aranda,Calle 13,35.0
4,C80755314,MOLINA RONALD,2016-09-01,14,LL-TCA-0132,NO UTILIZAR,101.0,LLANTA,4.0,362069.0,Suba,Suba,32.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
127250,C891100881,MORENO VARGAS SOCIEDAD ANONIMA,2020-03-10,2,LL-PLC-0159,X WORKS HD XDY 12R22.5,101.0,LLANTA,4.0,5635766.0,Engativa,Ventas externas,22.0
127251,C900364615,ORGANIZACION SUMA SAS,2020-03-10,1,LL-PLB-0024,X MULTI Z 235/75R17.5,101.0,LLANTA,9.0,6894000.0,Engativa,Ventas externas,22.0
127252,C900365651,EMPRESA DE TRANSPORTE INTEGRADO DE BOGOTA ETIB...,2020-03-10,2,LL-PLB-0024,X MULTI Z 235/75R17.5,101.0,LLANTA,20.0,11955636.0,Engativa,Ventas externas,22.0
127253,C900365651,EMPRESA DE TRANSPORTE INTEGRADO DE BOGOTA ETIB...,2020-03-10,2,LL-PLB-0031,XZE2 215/75 R17.5,101.0,LLANTA,30.0,15908063.0,Engativa,Ventas externas,22.0
127254,C900364615,ORGANIZACION SUMA SAS,2020-03-10,1,LL-PLC-0074,X MULTI Z 295/80R22.5,101.0,LLANTA,14.0,21868000.0,Engativa,Ventas externas,22.0

In [67]:
# Verifcamos que ahora Ventas es float
ventas.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 127255 entries, 0 to 127254
Data columns (total 13 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   IdCliente      127255 non-null  object
 1   NombreCliente  127255 non-null  object
 2   Fecha          127255 non-null  datetime64[ns]
 3   Empleado       127255 non-null  int64
 4   Referencia     127255 non-null  object
 5   Descripcion    127255 non-null  object
 6   CodigoFamilia  127255 non-null  float64
 7   Familia        127255 non-null  object
 8   Cantidad       127255 non-null  float64
 9   Ventas         127255 non-null  float64
 10  Localidad      127255 non-null  object
 11  Sede           127255 non-null  object
 12  Area           127255 non-null  float64
dtypes: datetime64[ns](1), float64(4), int64(1), object(7)
memory usage: 17.6+ MB

In [68]:
# Creamos la columna Ventas dólares ya que los valores están en pesos colombianos
ventas['Ventas_dólares'] = ventas['Ventas'] * 0.00023

<ipython-input-68-e5892b7df773>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  ventas['Ventas_dólares'] = ventas['Ventas'] * 0.00023

In [69]:
# Revisamos la suma de la columna
ventas["Ventas_dólares"].sum()

17117998.767079998

In [70]:
ventas["Ventas_dólares"].unique()

array([  29.7413 ,   41.63782,   44.41185, ..., 2749.79628, 3658.85449,
       5029.64   ])

In [72]:
# Revisamos el dataframe
ventas

,IdCliente,NombreCliente,Fecha,Empleado,Referencia,Descripcion,CodigoFamilia,Familia,Cantidad,Ventas,Localidad,Sede,Area,Ventas_dólares
0,C1070956433,PINTO JOHN,2016-09-01,24,LL-2R-0038,PILOT STREET 110/80-17,101.0,LLANTA,1.0,129310.0,Puente aranda,Calle 13,35.0,29.74130
1,C1032372566,CESAR CRUZ,2016-09-01,14,LL-TCA-0133,TOURING 175/70R13,101.0,LLANTA,2.0,181034.0,Suba,Suba,32.0,41.63782
2,C2865810,PINEDA JAIME,2016-09-01,12,LL-TCA-0019,ENERGY XM2 185/65R14,101.0,LLANTA,1.0,193095.0,Usaquen,Santa ana,33.0,44.41185
3,C11210285,VILLALBA RODRIGUEZ FABIO,2016-09-01,24,LL-TCA-0009,ENERGY XM2 165/65R13,101.0,LLANTA,2.0,262069.0,Puente aranda,Calle 13,35.0,60.27587
4,C80755314,MOLINA RONALD,2016-09-01,14,LL-TCA-0132,NO UTILIZAR,101.0,LLANTA,4.0,362069.0,Suba,Suba,32.0,83.27587
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
127250,C891100881,MORENO VARGAS SOCIEDAD ANONIMA,2020-03-10,2,LL-PLC-0159,X WORKS HD XDY 12R22.5,101.0,LLANTA,4.0,5635766.0,Engativa,Ventas externas,22.0,1296.22618
127251,C900364615,ORGANIZACION SUMA SAS,2020-03-10,1,LL-PLB-0024,X MULTI Z 235/75R17.5,101.0,LLANTA,9.0,6894000.0,Engativa,Ventas externas,22.0,1585.62000
127252,C900365651,EMPRESA DE TRANSPORTE INTEGRADO DE BOGOTA ETIB...,2020-03-10,2,LL-PLB-0024,X MULTI Z 235/75R17.5,101.0,LLANTA,20.0,11955636.0,Engativa,Ventas externas,22.0,2749.79628
127253,C900365651,EMPRESA DE TRANSPORTE INTEGRADO DE BOGOTA ETIB...,2020-03-10,2,LL-PLB-0031,XZE2 215/75 R17.5,101.0,LLANTA,30.0,15908063.0,Engativa,Ventas externas,22.0,3658.85449
127254,C900364615,ORGANIZACION SUMA SAS,2020-03-10,1,LL-PLC-0074,X MULTI Z 295/80R22.5,101.0,LLANTA,14.0,21868000.0,Engativa,Ventas externas,22.0,5029.64000

In [73]:
# Guardar el DataFrame en un archivo CSV
ventas.to_csv('ventaslimpias.csv', index=False)

In [ ]:
empleados = pd.read_csv("/content/Empleados.csv", sep=";")
empleados

    Id_Empleado   Nombre y Apellido
0             1        Juan Pastran
1             2      Esteban Damico
2             3      Julian Quevedo
3             4       Oscar Rosseto
4             5   Valentin Quintero
..          ...                 ...
63           64    Eduardo Monardez
64           65      Leonardo Perez
65           66  Rodolfo Colmenares
66           67        Esteban Vera
67           68        Adrian Ortiz

[68 rows x 2 columns]

In [ ]:
empleados.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68 entries, 0 to 67
Data columns (total 2 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id_Empleado        68 non-null     int64
 1   Nombre y Apellido  68 non-null     object
dtypes: int64(1), object(1)
memory usage: 1.2+ KB

In [ ]:
empleados.isna().sum()

Id_Empleado          0
Nombre y Apellido    0
dtype: int64

In [ ]:
# Guardar el DataFrame en un archivo CSV
empleados.to_csv('empleadoscsv.csv', index=False)